

DROP TABLE IF EXISTS user0;

CREATE TABLE user0
(
    id BIGINT(20) NOT NULL COMMENT 'ID',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    biz_id VARCHAR(50) NULL DEFAULT NULL COMMENT '业务区id,分片',
    PRIMARY KEY (id)
);


DROP TABLE IF EXISTS user1;

CREATE TABLE user1
(
    id BIGINT(20) NOT NULL COMMENT 'ID',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    biz_id VARCHAR(50) NULL DEFAULT NULL COMMENT '业务区id,分片',
    PRIMARY KEY (id)
);